# Generated by Django 3.0.8 on 2020-07-02 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('displayname', models.CharField(max_length=200)),
                ('emailID', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('videotitle', models.CharField(max_length=300)),
                ('videodesc', models.CharField(max_length=500)),
                ('videofile', models.FileField(blank=True, upload_to='video/%Y/%m/%d')),
                ('thumbnailimg', models.ImageField(blank=True, upload_to='video/%Y/%m/%d')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('vusername', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.CUser')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
