# Generated by Django 3.0.8 on 2020-07-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200709_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vusername',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.CUser'),
        ),
    ]
