# Generated by Django 3.0.8 on 2020-07-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200709_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('v_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='video.Video')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
